# Generated by Django 3.2.23 on 2024-01-16 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='uuid',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='insuranceapplication',
            old_name='uuid',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='uuid',
            new_name='uid',
        ),
    ]
